client_company_analysis:
  description: >
    Conduct a comprehensive analysis of the client's company, {client_name},
    including its market position, recent news, financial performance, and
    strategic initiatives.
  expected_output: >
    A comprehensive report on the client company's profile, including key strengths, 
    weaknesses, and potential areas for improvement.
    Including the company's current status, challenges, and
    opportunities, with specific insights relevant to product delivery and
    digital transformation.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: strategic_researcher

client_role_analysis:
  description: >
    Research and analyze the client: {contact_name}, his/her professional
    background, responsibilities, and potential priorities based on their role
    as {contact_role} and LinkedIn profile: {contact_linkedin}.
  expected_output: >
    A profile of the client including their career trajectory, areas of
    expertise, and likely strategic focus areas in their current role.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: strategic_researcher

industry_trend_analysis:
  description: >
    Identify and analyze key trends in the client's industry: {client_industry},
    particularly those related to agile methodologies, AI, cloud computing, and
    digital transformation.
  expected_output: >
    A report on industry trends, highlighting how they might impact the client's
    business and where agile product delivery could provide significant value.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: strategic_researcher

agile_strategy_development:
  description: >
    Develop a tailored agile product delivery strategy that addresses the
    specific needs and challenges identified in the client and company analysis.
  expected_output: >
    An overview of measures the client and his/her company can take to align
    themselves more with an agile operating model, including implementation
    roadmap, expected benefits, and potential challenges.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: agile_product_delivery_expert

value_proposition_creation:
  description: >
    Craft a compelling value proposition that clearly articulates how the
    consultant's expertise can address the client's specific needs and drive business value.
  expected_output: >
    A concise, powerful value proposition statement supported by relevant case
    studies and quantifiable benefits.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: agile_product_delivery_expert

meeting_agenda_creation:
  description: >
    Design a strategic meeting agenda that effectively balances
    relationship-building, information gathering, and value demonstration.
  expected_output: >
    A detailed meeting agenda with time allocations, key discussion points, and
    specific goals for each segment of the meeting.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: meeting_strategist

engagement_strategy_formulation:
  description: >
    Develop a comprehensive strategy for engaging with the client before, during and
    after the meeting, including follow-up actions and long-term relationship
    building tactics.
  expected_output: >
    An engagement playbook outlining conversation strategies, potential
    objections and responses, and a plan for post-meeting follow-up and
    nurturing.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: meeting_strategist

final_briefing_compilation:
  description: >
    Synthesize all insights, strategies, and plans into a cohesive final
    briefing document for the consultant.
  expected_output: >
    A comprehensive, easy-to-navigate briefing document that equips the
    consultant with all necessary information and strategies for a successful
    client meeting.
    Use markdown formatting in your response:                                                                                                                                                                                              
    - Use ## for main sections
    - Use ### for subsections
    - Use bullet points or numbered lists for key points
    - Use **bold** for important terms or figures
    - Use `code blocks` for any technical information or data
    - Use > for notable quotes or insights
    Present your findings in a clear, well-structured manner.
  agent: agile_product_delivery_expert
